### PR TITLE
influxdb tag/field tweaks to support new comparison feature

### PR DESCRIPTION
**Pull request by eostermueller**
Hi,

I made some tweaks to your code and am presenting the new "metric comparison" features at this conference in early next month (May):

https://saturn2018.sched.com/event/CaQU/finally-compare-todays-performance-to-yesterdays

Here is an overview on how to install:

https://github.com/eostermueller/applesToApples

I think I've kept these small changes from breaking your base functionality -- if not, please let me know.

--Erik

### CODE REVIEW

**Comment by Amaradana** [comment]
Happy to see this feature added, I have build a jar file, but when i tested this i get an error. please find the below error

java.lang.NoClassDefFoundError: org/influxdb/InfluxDBFactory
	at rocks.nt.apm.jmeter.JMeterInfluxDBBackendListenerClient.setupInfluxClient(JMeterInfluxDBBackendListenerClient.java:243) ~[JMeter-InfluxDB-Writer-master-1.2x.jar:1.2x]
	at rocks.nt.apm.jmeter.JMeterInfluxDBBackendListenerClient.setupTest(JMeterInfluxDBBackendListenerClient.java:174) ~[JMeter-InfluxDB-Writer-master-1.2x.jar:1.2x]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:337) ~[ApacheJMeter_components.jar:4.0 r1823414]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:292) ~[ApacheJMeter_components.jar:4.0 r1823414]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:215) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:384) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

I tried with Jmeter 3.3 and 4.0.

When is this actual release is going to be? Also if it takes to long please let me know if i have to change something i could do that

**Comment by eostermueller** [comment]
My presentation is this Tuesday, so I'd like to fix this in the next few days so the people I'm presenting to can use your release instead of mine.

Would you test my release jar and see if that works for you?
https://github.com/eostermueller/JMeter-InfluxDB-Writer/releases/download/v-1.2x/JMeter-InfluxDB-Writer-plugin-1.2x.jar

I'll take a closer look tonight.
--Erik

**Comment by Amaradana** [comment]
I checked with your jar, it's working fine but I haven't setup your dashboard as we don't have access to install anything in office. I will check your dashboard in weekend and let you know.

If you could help me to build the jar I wanted to do some changes and generate jar file accordingly as per our requirements.  That would be helpful.

**Comment by eostermueller** [comment]
Could you send me your broken jar?
I can't reproduce your issue.
Thanks,
--Erik

**Comment by eostermueller** [comment]
ok, I can reproduce this now on my mac....but it works elsewhere.
No need to send the jar.

**Comment by eostermueller** [comment]
Here's what I did to reproduce the error -- I put the wrong jar in JMETER_HOME/lib/ext
The wrong one is first -- see how small it is?  I built that with './gradlew clean build'.
I got the second one to work -- built that with './gradlew fatJar'

Would you see if this was your problem?
```
-rw-r--r--  1 erikostermueller  staff    16747 May  5 11:00 JMeter-InfluxDB-Writer-1.2x.jar
-rw-r--r--  1 erikostermueller  staff  3313958 May  5 13:06 JMeter-InfluxDB-Writer-plugin-1.2x.jar

```
Thanks,
--Erik

**Comment by Amaradana** [comment]
hi,

Am using windows, in my case i think i did in wrong way, I will retry today, Also am curious to see what dashboard have you build, is there a way where we can just use json?

**Comment by eostermueller** [comment]
I didn't understand your comment when I read it earlier -- but the answer is no, it won't work, it will paint empty graphs w/o any data.

If you look at step 6 on [this page](https://github.com/eostermueller/applesToApples).

It shows you need to hit the following URL to get the right graphs:

http://localhost:3000/dashboard/script/applesToApples.js?testName=FantasticLoadTest

This is a Grafana "Scripted Dashboard", as detailed [here](http://docs.grafana.org/reference/scripting/), and it invokes [a javascript file](https://github.com/eostermueller/applesToApples/blob/master/applesToApples.js) that I wrote, which first queries influxdb for a list of the 'runId' values for the given testName.  Then it uses those values to create the json for the dashboard.

**Pull request merged**
